# Generated by Django 2.2 on 2019-04-30 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('image', models.ImageField(default='SOME STRING', upload_to='uploaded_images/')),
                ('available_balance', models.IntegerField()),
            ],
        ),
    ]
