# Generated by Django 2.2 on 2019-04-30 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmethod',
            name='currency_name',
            field=models.CharField(blank=True, choices=[('BDT', 'BDT'), ('USD', 'USD')], max_length=1, null=True),
        ),
    ]
