# Generated by Django 2.2 on 2019-05-09 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0004_auto_20190509_0415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmethod',
            name='weight',
            field=models.CharField(blank=True, choices=[('Gram', 'Gram')], max_length=10, null=True),
        ),
    ]
