# Generated by Django 2.2 on 2019-05-09 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0005_auto_20190509_0416'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmethod',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
