# Generated by Django 2.2 on 2019-05-09 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0006_paymentmethod_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmethod',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
