# Generated by Django 2.2 on 2019-05-15 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0010_exchangerate'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchangerate',
            name='is_available',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
