# Generated by Django 2.2 on 2019-05-22 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0011_exchangerate_is_available'),
    ]

    operations = [
        migrations.CreateModel(
            name='transactionForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('phone', models.IntegerField()),
                ('sendAmount', models.IntegerField()),
                ('sendFrom', models.CharField(max_length=100)),
                ('receiveAmount', models.IntegerField()),
                ('receiveFrom', models.CharField(max_length=100)),
            ],
        ),
    ]
