# Generated by Django 2.2 on 2019-05-22 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0012_transactionform'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionform',
            name='transaction_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
