# Generated by Django 2.2 on 2019-05-22 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0013_transactionform_transaction_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionform',
            name='status',
            field=models.CharField(blank=True, choices=[('Processing', 'Processing'), ('Done', 'Done'), ('Failed', 'Failed')], default='Processing', max_length=10, null=True),
        ),
    ]
