# Generated by Django 2.2 on 2019-05-22 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0015_auto_20190522_0636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionform',
            name='phone',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='transactionform',
            name='sendAmount',
            field=models.IntegerField(),
        ),
    ]
