# Generated by Django 2.2 on 2019-05-22 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0016_auto_20190522_0656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionform',
            name='phone',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='transactionform',
            name='sendAmount',
            field=models.CharField(max_length=100),
        ),
    ]
