# Generated by Django 2.2 on 2019-05-22 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0017_auto_20190522_0706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionform',
            name='sendAmount',
            field=models.IntegerField(),
        ),
    ]
