# Generated by Django 2.2 on 2019-05-22 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0018_auto_20190522_0718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionform',
            name='receiveAmount',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='transactionform',
            name='sendAmount',
            field=models.CharField(max_length=100),
        ),
    ]
