# Generated by Django 2.2 on 2019-05-27 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0020_auto_20190526_0953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionform',
            name='receiveAmount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='transactionform',
            name='sendAmount',
            field=models.IntegerField(),
        ),
    ]
