# Generated by Django 2.2 on 2019-05-28 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0021_auto_20190527_0552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionform',
            name='receiveAmount',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='transactionform',
            name='sendAmount',
            field=models.FloatField(),
        ),
    ]
